services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MediLabo_Strong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'MediLabo_Strong@Passw0rd' -Q 'SELECT 1' -No"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - medilabo-network

  patientservice:
    build: ./src/Microservices/PatientService
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Projet10_PatientDb;User Id=sa;Password=MediLabo_Strong@Passw0rd;TrustServerCertificate=True
      - Jwt__Key=MedilaboSuperSecretKey12345678901
      - Jwt__Issuer=AuthService
      - Jwt__Audience=MedilaboApp
    networks:
      - medilabo-network

  authservice:
    build: ./src/Microservices/AuthService
    depends_on:
      sqlserver :
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Projet10_AuthDb;User Id=sa;Password=MediLabo_Strong@Passw0rd;TrustServerCertificate=True
      - Jwt__Key=MedilaboSuperSecretKey12345678901
      - Jwt__Issuer=AuthService
      - Jwt__Audience=MedilaboApp
    networks:
      - medilabo-network

  gatewayservice:
    build: ./src/Microservices/GatewayService
    ports:
      - "5000:8080"
    depends_on:
      - patientservice
      - authservice
      - noteservice
      - riskservice
    environment:
      - Jwt__Key=MedilaboSuperSecretKey12345678901
      - Jwt__Issuer=AuthService
      - Jwt__Audience=MedilaboApp
    networks:
      - medilabo-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - medilabo-network

  noteservice:
    build: ./src/Microservices/NoteService
    depends_on:
      - mongodb
    environment:
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017
      - MongoDB__DatabaseName=Projet10_NoteDb
      - Jwt__Key=MedilaboSuperSecretKey12345678901
      - Jwt__Issuer=AuthService
      - Jwt__Audience=MedilaboApp
    networks:
      - medilabo-network

  riskservice:
    build: ./src/Microservices/RiskService
    environment:
      - GatewayUrl=http://gatewayservice:8080
      - Jwt__Key=MedilaboSuperSecretKey12345678901
      - Jwt__Issuer=AuthService
      - Jwt__Audience=MedilaboApp
    networks:
      - medilabo-network

  frontendservice:
    build: ./src/Microservices/FrontendService
    ports:
      - "5003:8080"
    depends_on:
      - gatewayservice
    environment:
      - GatewayUrl=http://gatewayservice:8080
    networks:
      - medilabo-network

networks:
  medilabo-network:
    driver: bridge

volumes :
  mongo-data:
  mssql-data: 